apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "my-limit-range"
spec:
  limits:
    - default:
        memory: "512Mi"
        cpu: "200m"
      defaultRequest:
        memory: "256Mi"
        cpu: "100m"
      type: "Pod"
