apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "my-limit-range" 
spec:
  limits:
    -
      type: "Pod"
      max:
        cpu: "2" 
        memory: "256Mi" 
      min:
        cpu: "50m" 
        memory: "6Mi" 
    -
      type: "Container"
      max:
        cpu: "2" 
        memory: "256Mi" 
      min:
        cpu: "100m" 
        memory: "4Mi" 
      default:
        cpu: "300m" 
        memory: "200Mi" 
      defaultRequest:
        cpu: "200m" 
        memory: "100Mi" 
      maxLimitRequestRatio:
        cpu: "10" 