apiVersion: v1
kind: LimitRange
metadata:
  name: my-limit-range
spec:
  limits:
    -
      type: Pod
      max:
        cpu: 200m
        memory: 256Mi
      min:
        cpu: 50m 
        memory: 6Mi